import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Header from "./components/Header";
import Providers from "./provider";
import localFont from "next/font/local";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const no_name_reg = localFont({
  src: "../public/fonts/no_name_37_Regular.otf",
  variable: "--font-no-name-regular",
})

const open_sans_semibold = localFont({
  src: "../public/fonts/OpenSans-Semibold.ttf",
  variable: "--font-open-sans-semibold",
})

const open_sans_regular = localFont({
  src: "../public/fonts/OpenSans-Regular.ttf",
  variable: "--font-open-sans-regular",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={`${open_sans_regular.variable} ${no_name_reg.variable} ${open_sans_semibold.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        
        <div className="h-screen flex flex-col">
        <Header></Header>
        <main className="flex-1 overflow-auto">
          {children}
        </main>
      </div>
      <Toaster/>
      </Providers>
      </body>
    </html>
  );
}

